### ISSUE TITLE
Maybe cover the rest of TestSwarm API?..

### ISSUE THREAD

**Issue by jayarjo** [jzaefferer/node-testswarm#5]
For our case we required some additional methods, so I basically covered the whole API, or a big part of it at least (TestSwarm itself quite raw for console usage). Here: https://github.com/jayarjo/bunyip/blob/master/lib/testswarm.js. Your module gave initial inspiration, I've even retained namings for some methods :)

Would you be interested to pull that in as an update maybe?

**Comment by Krinkle** [comment]
Closing old issues and pull requests relating to TestSwarm.

Per <https://github.com/jquery/testswarm>, additional features are no longer considered.
Small bug fixes are still welcome, though!
